// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type ConfigureCodeSamplesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	GithubConfigureCodeSamplesResponse *shared.GithubConfigureCodeSamplesResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ConfigureCodeSamplesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ConfigureCodeSamplesResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ConfigureCodeSamplesResponse) GetGithubConfigureCodeSamplesResponse() *shared.GithubConfigureCodeSamplesResponse {
	if o == nil {
		return nil
	}
	return o.GithubConfigureCodeSamplesResponse
}

func (o *ConfigureCodeSamplesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ConfigureCodeSamplesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
