// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetChangesReportSignedURLRequest struct {
	// The checksum of the document to retrieve the signed access url for.
	DocumentChecksum string `pathParam:"style=simple,explode=false,name=documentChecksum"`
}

func (o *GetChangesReportSignedURLRequest) GetDocumentChecksum() string {
	if o == nil {
		return ""
	}
	return o.DocumentChecksum
}

// GetChangesReportSignedURLSignedAccess - OK
type GetChangesReportSignedURLSignedAccess struct {
	URL string `json:"url"`
}

func (o *GetChangesReportSignedURLSignedAccess) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

type GetChangesReportSignedURLResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SignedAccess *GetChangesReportSignedURLSignedAccess
}

func (o *GetChangesReportSignedURLResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetChangesReportSignedURLResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetChangesReportSignedURLResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetChangesReportSignedURLResponse) GetSignedAccess() *GetChangesReportSignedURLSignedAccess {
	if o == nil {
		return nil
	}
	return o.SignedAccess
}
