// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/pkg/models/shared"
	"net/http"
)

type GetPluginsResponse struct {
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	Plugins     []shared.Plugin
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetPluginsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPluginsResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetPluginsResponse) GetPlugins() []shared.Plugin {
	if o == nil {
		return nil
	}
	return o.Plugins
}

func (o *GetPluginsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPluginsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
