// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetWorkspaceEventsBySourceRevisionDigestGlobals struct {
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

func (o *GetWorkspaceEventsBySourceRevisionDigestGlobals) GetWorkspaceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

type GetWorkspaceEventsBySourceRevisionDigestRequest struct {
	// Unique identifier of the source revision digest.
	SourceRevisionDigest string `pathParam:"style=simple,explode=false,name=sourceRevisionDigest"`
	// Unique identifier of the workspace.
	WorkspaceID *string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

func (o *GetWorkspaceEventsBySourceRevisionDigestRequest) GetSourceRevisionDigest() string {
	if o == nil {
		return ""
	}
	return o.SourceRevisionDigest
}

func (o *GetWorkspaceEventsBySourceRevisionDigestRequest) GetWorkspaceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

type GetWorkspaceEventsBySourceRevisionDigestResponse struct {
	// Success
	CliEventBatch []shared.CliEvent
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetWorkspaceEventsBySourceRevisionDigestResponse) GetCliEventBatch() []shared.CliEvent {
	if o == nil {
		return nil
	}
	return o.CliEventBatch
}

func (o *GetWorkspaceEventsBySourceRevisionDigestResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetWorkspaceEventsBySourceRevisionDigestResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetWorkspaceEventsBySourceRevisionDigestResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
