// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"time"
)

type Claims struct {
}

type AccessTokenUser struct {
	Admin         *bool      `json:"admin,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	DisplayName   *string    `json:"display_name,omitempty"`
	Email         *string    `json:"email,omitempty"`
	EmailVerified *bool      `json:"email_verified,omitempty"`
	ID            *string    `json:"id,omitempty"`
}

func (a AccessTokenUser) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccessTokenUser) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccessTokenUser) GetAdmin() *bool {
	if o == nil {
		return nil
	}
	return o.Admin
}

func (o *AccessTokenUser) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *AccessTokenUser) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *AccessTokenUser) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *AccessTokenUser) GetEmailVerified() *bool {
	if o == nil {
		return nil
	}
	return o.EmailVerified
}

func (o *AccessTokenUser) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

type Workspaces struct {
}

// An AccessToken is a token that can be used to authenticate with the Speakeasy API.
type AccessToken struct {
	AccessToken string          `json:"access_token"`
	Claims      Claims          `json:"claims"`
	User        AccessTokenUser `json:"user"`
	Workspaces  []Workspaces    `json:"workspaces,omitempty"`
}

func (o *AccessToken) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *AccessToken) GetClaims() Claims {
	if o == nil {
		return Claims{}
	}
	return o.Claims
}

func (o *AccessToken) GetUser() AccessTokenUser {
	if o == nil {
		return AccessTokenUser{}
	}
	return o.User
}

func (o *AccessToken) GetWorkspaces() []Workspaces {
	if o == nil {
		return nil
	}
	return o.Workspaces
}
