// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AccountType string

const (
	AccountTypeFree       AccountType = "free"
	AccountTypeScaleUp    AccountType = "scale-up"
	AccountTypeBusiness   AccountType = "business"
	AccountTypeEnterprise AccountType = "enterprise"
)

func (e AccountType) ToPointer() *AccountType {
	return &e
}
