// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Annotations
type Annotations struct {
	OrgOpencontainersImageAuthors       *string `json:"org.opencontainers.image.authors,omitempty"`
	OrgOpencontainersImageBaseDigest    *string `json:"org.opencontainers.image.base.digest,omitempty"`
	OrgOpencontainersImageBaseName      *string `json:"org.opencontainers.image.base.name,omitempty"`
	OrgOpencontainersImageCreated       *string `json:"org.opencontainers.image.created,omitempty"`
	OrgOpencontainersImageDescription   *string `json:"org.opencontainers.image.description,omitempty"`
	OrgOpencontainersImageDocumentation *string `json:"org.opencontainers.image.documentation,omitempty"`
	OrgOpencontainersImageLicenses      *string `json:"org.opencontainers.image.licenses,omitempty"`
	OrgOpencontainersImageRefName       *string `json:"org.opencontainers.image.ref.name,omitempty"`
	OrgOpencontainersImageRevision      *string `json:"org.opencontainers.image.revision,omitempty"`
	OrgOpencontainersImageSource        *string `json:"org.opencontainers.image.source,omitempty"`
	OrgOpencontainersImageTitle         *string `json:"org.opencontainers.image.title,omitempty"`
	OrgOpencontainersImageURL           *string `json:"org.opencontainers.image.url,omitempty"`
	OrgOpencontainersImageVendor        *string `json:"org.opencontainers.image.vendor,omitempty"`
	OrgOpencontainersImageVersion       *string `json:"org.opencontainers.image.version,omitempty"`
}

func (o *Annotations) GetOrgOpencontainersImageAuthors() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageAuthors
}

func (o *Annotations) GetOrgOpencontainersImageBaseDigest() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageBaseDigest
}

func (o *Annotations) GetOrgOpencontainersImageBaseName() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageBaseName
}

func (o *Annotations) GetOrgOpencontainersImageCreated() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageCreated
}

func (o *Annotations) GetOrgOpencontainersImageDescription() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageDescription
}

func (o *Annotations) GetOrgOpencontainersImageDocumentation() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageDocumentation
}

func (o *Annotations) GetOrgOpencontainersImageLicenses() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageLicenses
}

func (o *Annotations) GetOrgOpencontainersImageRefName() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageRefName
}

func (o *Annotations) GetOrgOpencontainersImageRevision() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageRevision
}

func (o *Annotations) GetOrgOpencontainersImageSource() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageSource
}

func (o *Annotations) GetOrgOpencontainersImageTitle() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageTitle
}

func (o *Annotations) GetOrgOpencontainersImageURL() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageURL
}

func (o *Annotations) GetOrgOpencontainersImageVendor() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageVendor
}

func (o *Annotations) GetOrgOpencontainersImageVersion() *string {
	if o == nil {
		return nil
	}
	return o.OrgOpencontainersImageVersion
}
