// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetTagsResponse struct {
	Items []Tag `json:"items"`
}

func (o *GetTagsResponse) GetItems() []Tag {
	if o == nil {
		return []Tag{}
	}
	return o.Items
}
