// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GithubStorePublishingSecretsRequest - A request to store publishing secrets for a github target
type GithubStorePublishingSecretsRequest struct {
	// The generation lock ID
	GenerateGenLockID string `json:"generate_gen_lock_id"`
	// A map of secrets to store in the GitHub target
	Secrets map[string]string `json:"secrets,omitempty"`
}

func (o *GithubStorePublishingSecretsRequest) GetGenerateGenLockID() string {
	if o == nil {
		return ""
	}
	return o.GenerateGenLockID
}

func (o *GithubStorePublishingSecretsRequest) GetSecrets() map[string]string {
	if o == nil {
		return nil
	}
	return o.Secrets
}
