// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GithubConfigureTargetRequest - A request to configure a GitHub target
type GithubConfigureTargetRequest struct {
	// The GitHub organization name
	Org string `json:"org"`
	// The GitHub repository name
	RepoName string `json:"repo_name"`
}

func (o *GithubConfigureTargetRequest) GetOrg() string {
	if o == nil {
		return ""
	}
	return o.Org
}

func (o *GithubConfigureTargetRequest) GetRepoName() string {
	if o == nil {
		return ""
	}
	return o.RepoName
}
