// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GithubPublishingPRResponse - Open generation PRs pending publishing
type GithubPublishingPRResponse struct {
	GenerationPullRequest *string `json:"generation_pull_request,omitempty"`
	PendingVersion        *string `json:"pending_version,omitempty"`
}

func (o *GithubPublishingPRResponse) GetGenerationPullRequest() *string {
	if o == nil {
		return nil
	}
	return o.GenerationPullRequest
}

func (o *GithubPublishingPRResponse) GetPendingVersion() *string {
	if o == nil {
		return nil
	}
	return o.PendingVersion
}
