// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Manifest - Returns the requested manifest file
type Manifest struct {
	// Annotations
	Annotations *Annotations `json:"annotations,omitempty"`
	// Type of artifact
	ArtifactType *string `json:"artifactType,omitempty"`
	// List of V2 image layer information
	Layers []V2Descriptor `json:"layers,omitempty"`
	// Media type usually application/vnd.docker.distribution.manifest.v2+json if this is in the accept header
	MediaType *string `json:"mediaType,omitempty"`
	// Schema version
	SchemaVersion *int64 `json:"schemaVersion,omitempty"`
}

func (o *Manifest) GetAnnotations() *Annotations {
	if o == nil {
		return nil
	}
	return o.Annotations
}

func (o *Manifest) GetArtifactType() *string {
	if o == nil {
		return nil
	}
	return o.ArtifactType
}

func (o *Manifest) GetLayers() []V2Descriptor {
	if o == nil {
		return nil
	}
	return o.Layers
}

func (o *Manifest) GetMediaType() *string {
	if o == nil {
		return nil
	}
	return o.MediaType
}

func (o *Manifest) GetSchemaVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.SchemaVersion
}
