// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type License struct {
	Identifier *string `json:"identifier,omitempty"`
}

func (o *License) GetIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.Identifier
}

type OASInfo struct {
	Description string  `json:"description"`
	License     License `json:"license"`
	Summary     string  `json:"summary"`
	Title       string  `json:"title"`
	Version     string  `json:"version"`
}

func (o *OASInfo) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *OASInfo) GetLicense() License {
	if o == nil {
		return License{}
	}
	return o.License
}

func (o *OASInfo) GetSummary() string {
	if o == nil {
		return ""
	}
	return o.Summary
}

func (o *OASInfo) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *OASInfo) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}
