// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OASOperation struct {
	Description        string   `json:"description"`
	GroupOverride      *string  `json:"group_override,omitempty"`
	Method             string   `json:"method"`
	MethodNameOverride *string  `json:"method_name_override,omitempty"`
	OperationID        string   `json:"operation_id"`
	Path               string   `json:"path"`
	Tags               []string `json:"tags"`
}

func (o *OASOperation) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *OASOperation) GetGroupOverride() *string {
	if o == nil {
		return nil
	}
	return o.GroupOverride
}

func (o *OASOperation) GetMethod() string {
	if o == nil {
		return ""
	}
	return o.Method
}

func (o *OASOperation) GetMethodNameOverride() *string {
	if o == nil {
		return nil
	}
	return o.MethodNameOverride
}

func (o *OASOperation) GetOperationID() string {
	if o == nil {
		return ""
	}
	return o.OperationID
}

func (o *OASOperation) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *OASOperation) GetTags() []string {
	if o == nil {
		return []string{}
	}
	return o.Tags
}
