// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrganizationUsage struct {
	// Indicates if the features are accessible
	Accessible bool `json:"accessible"`
	// Features that are accessible
	AccessibleFeatures []string `json:"accessible_features"`
	// List of generation lock IDs
	GenLockIds []string `json:"gen_lock_ids"`
	// The programming language used
	Language string `json:"language"`
	// Number of operations performed
	NumberOfOperations int64 `json:"number_of_operations"`
	// Features that have been used
	UsedFeatures []string `json:"used_features"`
	// List of workspace IDs
	Workspaces []string `json:"workspaces"`
}

func (o *OrganizationUsage) GetAccessible() bool {
	if o == nil {
		return false
	}
	return o.Accessible
}

func (o *OrganizationUsage) GetAccessibleFeatures() []string {
	if o == nil {
		return []string{}
	}
	return o.AccessibleFeatures
}

func (o *OrganizationUsage) GetGenLockIds() []string {
	if o == nil {
		return []string{}
	}
	return o.GenLockIds
}

func (o *OrganizationUsage) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

func (o *OrganizationUsage) GetNumberOfOperations() int64 {
	if o == nil {
		return 0
	}
	return o.NumberOfOperations
}

func (o *OrganizationUsage) GetUsedFeatures() []string {
	if o == nil {
		return []string{}
	}
	return o.UsedFeatures
}

func (o *OrganizationUsage) GetWorkspaces() []string {
	if o == nil {
		return []string{}
	}
	return o.Workspaces
}
