// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-api/speakeasy-client-sdk-go/v3/pkg/utils"
	"time"
)

// Organization - A speakeasy organization
type Organization struct {
	AccountType       AccountType `json:"account_type"`
	CreatedAt         *time.Time  `json:"created_at,omitempty"`
	FreeTrialExpiry   *time.Time  `json:"free_trial_expiry,omitempty"`
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Slug              *string     `json:"slug,omitempty"`
	TelemetryDisabled bool        `json:"telemetry_disabled"`
	UpdatedAt         *time.Time  `json:"updated_at,omitempty"`
}

func (o Organization) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Organization) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Organization) GetAccountType() AccountType {
	if o == nil {
		return AccountType("")
	}
	return o.AccountType
}

func (o *Organization) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Organization) GetFreeTrialExpiry() *time.Time {
	if o == nil {
		return nil
	}
	return o.FreeTrialExpiry
}

func (o *Organization) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Organization) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Organization) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *Organization) GetTelemetryDisabled() bool {
	if o == nil {
		return false
	}
	return o.TelemetryDisabled
}

func (o *Organization) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
