// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// A PreflightToken is a token that allows access to the OCI distribution endpoints.
type PreflightToken struct {
	AccessToken string `json:"access_token"`
}

func (o *PreflightToken) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}
