// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SuggestedOperationIDs struct {
	OperationIds map[string][]string `json:"operation_ids"`
}

func (o *SuggestedOperationIDs) GetOperationIds() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.OperationIds
}
