// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Tag struct {
	// Format {namespace_id}/{tag}
	ID string `json:"id"`
	// Human readable tag name
	Name           string `json:"name"`
	NamespaceName  string `json:"namespace_name"`
	RevisionDigest string `json:"revision_digest"`
}

func (o *Tag) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Tag) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Tag) GetNamespaceName() string {
	if o == nil {
		return ""
	}
	return o.NamespaceName
}

func (o *Tag) GetRevisionDigest() string {
	if o == nil {
		return ""
	}
	return o.RevisionDigest
}
