// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Auth struct {
	Header string `json:"header"`
	Secret string `json:"secret"`
}

func (o *Auth) GetHeader() string {
	if o == nil {
		return ""
	}
	return o.Header
}

func (o *Auth) GetSecret() string {
	if o == nil {
		return ""
	}
	return o.Secret
}

// WorkflowDocument - A document referenced by a workflow
type WorkflowDocument struct {
	Auth     *Auth  `json:"auth,omitempty"`
	Location string `json:"location"`
}

func (o *WorkflowDocument) GetAuth() *Auth {
	if o == nil {
		return nil
	}
	return o.Auth
}

func (o *WorkflowDocument) GetLocation() string {
	if o == nil {
		return ""
	}
	return o.Location
}
